# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bio_data', '0002_farmerbiodata_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('details', models.CharField(max_length=75)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_data.FarmerBioData')),
            ],
        ),
        migrations.CreateModel(
            name='FarmField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('1', 'kharif'), ('2', 'rabi'), ('3', 'winter')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('field_from', models.DateTimeField()),
                ('field_to', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_field.Farm')),
            ],
        ),
    ]
