# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmfield',
            name='crop_type',
            field=models.CharField(choices=[('1', 'Millets (Bajra & Jowar)'), ('2', 'Cotton'), ('3', 'Soyabean'), ('4', 'Sugarcane'), ('5', 'Turmeric'), ('6', 'Paddy (Rice)'), ('7', 'Maize'), ('8', 'Moong (Pulses)'), ('9', 'Groundnut'), ('10', 'Red Chillies'), ('11', 'Wheat'), ('12', 'Peas')], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmfield',
            name='land_coordinates',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='farmfield',
            name='season',
            field=models.CharField(choices=[('1', 'kharif'), ('2', 'rabi'), ('3', 'winter')], max_length=2),
        ),
    ]
