# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_field', '0002_auto_20171002_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmfield',
            name='name',
            field=models.CharField(default='name', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmfield',
            name='field_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='farmfield',
            name='field_to',
            field=models.DateField(),
        ),
    ]
