# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_field', '0003_auto_20171002_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='bio_data.FarmerBioData'),
        ),
        migrations.AlterField(
            model_name='farmfield',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmfield', to='farm_field.Farm'),
        ),
    ]
