# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerbiodata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
